version: "3.9"
services:
  database:
    image: postgres
    user: root
    env_file:
      - .env.docker
    volumes:
      - ./../volumes/database:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    user: root
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .env.docker
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./../cache:/data
  web:
    build:
      context: .
      dockerfile: .docker/ror/Dockerfile
    env_file:
    - .env.docker
    volumes:
      - .:/ror
    ports:
      - "3000:3000"
    depends_on:
      - database
      - cache